POST http://localhost:7000/api/v1/users/register HTTP/1.1
# content-type: application/json

# {
#     "userName": "tondv",
#     "emailAddress": "ton@gmail.com",
#     "accountNumber": "35345",
#     "identityNumber": "634"
# }

# GET http://localhost:7000/api/v1/users HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MzA4NjdjYzI1ODcyMjFjMTk1ZjY5MSIsInVzZXJuYW1lIjoidG9uIiwiaWF0IjoxNzMxMjMzNDA0LCJleHAiOjE3MzM4MjU0MDR9.EFo_KjRpUBLN4ik7d5gig96PbReSVQsd9u29furN8qE